### ISSUE TITLE
Snyk found issue in intel@1.2.0

### ISSUE THREAD

**Issue by LmKupke** [postmanlabs/postman-collection-transformer#252]
When running snyk it found a medium severity issue in the Postman-collection-transformer package. The package uses intel 1.2.0 which has a dependency on dbug@0.4.2 . This dependency is no longer maintained.

This issue that is cited in the security scan is the MPL-2.0 license. My suggestion is to use a different logger than intel.

![Screen Shot 2019-11-18 at 3 35 46 PM](https://user-images.githubusercontent.com/7860541/69091968-6436e200-0a19-11ea-8054-f93202851299.png)

**Comment by codenirvana** [comment]
Fixed in v4.
