### ISSUE TITLE
transform-collection: command not found

### ISSUE THREAD

**Issue by chaseTfreeman** [postmanlabs/postman-collection-transformer#359]
**npm install -g postman-collection-transformer** 

I'm stuck trying to convert my collections to V2. I install the package and run the command like the README says and I get nothing in return. `transform-collection convert -h`

Please advise

**Comment by surbhi114** [comment]
The name in package.json is "postman-collection-transformer", I think this is a bug in README, needs to be fixed.

**Comment by codenirvana** [comment]
@surbhi114 Right, the command is `postman-collection-transformer` not `transform-collection`.
Updated the README.
