### ISSUE TITLE
Not Installing on Map

### ISSUE THREAD

**Issue by Hardcastle-GIS** [postmanlabs/postman-collection-transformer#380]
Hi 

I tried installing Postman Transfomer on my Mac but couldn't. 
----------------------------------------------------------------------------------
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/postman-collection-transfomer - Not found
npm ERR! 404 
npm ERR! 404  'postman-collection-transfomer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
----------------------------------------------------------------------------------

**Comment by codenirvana** [comment]
There's a typo in the package name, it's `transformer` not `transfomer`.

Try this: `npm install -g postman-collection-transformer`
